# Generated by Django 5.1.3 on 2025-02-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(default='../default_avatar', upload_to='images/'),
        ),
    ]
