# Generated by Django 4.2 on 2025-02-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_users_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
